In [64]:
import pandas as pd

In [65]:
stats = pd.read_csv("player_mvp_stats.csv")
# df = pd.read_csv("player_mvp_stats.csv")
# # Filter out rows where any column contains 2024
# df = df[df.apply(lambda row: 2024 not in row.values, axis=1)]

# # Save the filtered CSV
# df.to_csv('no2024_file.csv', index=False)

In [66]:
stats

,Unnamed: 0,Player,Age,Team,Pos,G,GS,MP,FG,FGA,...,Pts Won,Pts Max,Share,W,L,W/L%,GB,PS/G,PA/G,SRS
0,0,A.C. Green,27.0,Los Angeles Lakers,PF,82.0,21.0,26.4,3.1,6.6,...,0.0,0.0,0.000,58.0,24.0,0.707,5.0,106.3,99.6,6.73
1,1,Byron Scott,29.0,Los Angeles Lakers,SG,82.0,82.0,32.1,6.1,12.8,...,0.0,0.0,0.000,58.0,24.0,0.707,5.0,106.3,99.6,6.73
2,2,Elden Campbell,22.0,Los Angeles Lakers,PF,52.0,0.0,7.3,1.1,2.4,...,0.0,0.0,0.000,58.0,24.0,0.707,5.0,106.3,99.6,6.73
3,3,Irving Thomas,25.0,Los Angeles Lakers,PF,26.0,0.0,4.2,0.7,1.9,...,0.0,0.0,0.000,58.0,24.0,0.707,5.0,106.3,99.6,6.73
4,4,James Worthy,29.0,Los Angeles Lakers,SF,78.0,74.0,38.6,9.2,18.7,...,0.0,0.0,0.000,58.0,24.0,0.707,5.0,106.3,99.6,6.73
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14115,14115,Luka DonÄiÄ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,146.0,1000.0,0.146,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14116,14116,Nikola JokiÄ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,674.0,1000.0,0.674,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14117,14117,Luka DonÄiÄ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,10.0,1000.0,0.010,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14118,14118,Nikola JokiÄ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,926.0,990.0,0.935,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14119,14119,Luka DonÄiÄ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,566.0,990.0,0.572,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [67]:
del stats["Unnamed: 0"]

In [68]:
# returning null items
pd.isnull(stats).sum()
# all % areas have higher numbers

Player         0
Age           24
Team          24
Pos           24
G             24
GS            24
MP            24
FG            24
FGA           24
FG%           89
3P            24
3PA           24
3P%         1941
2P            24
2PA           24
2P%          133
eFG%          89
FT            24
FTA           24
FT%          566
ORB           24
DRB           24
TRB           24
AST           24
STL           24
BLK           24
TOV           24
PF            24
PTS           24
Awards     12336
Year           0
Pts Won        0
Pts Max        0
Share          0
W             24
L             24
W/L%          24
GB            24
PS/G          24
PA/G          24
SRS           24
dtype: int64

In [69]:
# gets items where 3P% is null
stats[pd.isnull(stats["3P%"])][["Player", "3PA"]]

               Player  3PA
2      Elden Campbell  0.0
3       Irving Thomas  0.0
17         Jack Haley  0.0
19        Keith Owens  0.0
32      James Edwards  0.0
...               ...  ...
14115   Luka DonÄiÄ  NaN
14116   Nikola JokiÄ  NaN
14117   Luka DonÄiÄ  NaN
14118   Nikola JokiÄ  NaN
14119   Luka DonÄiÄ  NaN

[1941 rows x 2 columns]

In [70]:
# gets items where FT% is null
stats[pd.isnull(stats["FT%"])][["Player", "FTA"]]

                Player  FTA
74          John Coker  0.0
82     Adrian Caldwell  0.0
96        Bruno Šundov  0.0
134     Jamal Robinson  0.0
138      A.J. Bramlett  0.0
...                ...  ...
14115    Luka DonÄiÄ  NaN
14116    Nikola JokiÄ  NaN
14117    Luka DonÄiÄ  NaN
14118    Nikola JokiÄ  NaN
14119    Luka DonÄiÄ  NaN

[566 rows x 2 columns]

In [71]:
# fills in 0 for null values
stats = stats.fillna(0)

In [72]:
stats.columns

Index(['Player', 'Age', 'Team', 'Pos', 'G', 'GS', 'MP', 'FG', 'FGA', 'FG%',
       '3P', '3PA', '3P%', '2P', '2PA', '2P%', 'eFG%', 'FT', 'FTA', 'FT%',
       'ORB', 'DRB', 'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS', 'Awards',
       'Year', 'Pts Won', 'Pts Max', 'Share', 'W', 'L', 'W/L%', 'GB', 'PS/G',
       'PA/G', 'SRS'],
      dtype='object')

In [73]:
# explicit list of predictors
# had to remove string columns and Points Won and Shares since we are predicting those
# goal: predict percentage share MVP votes that a player got in a given year
predictors = ['Age', 'G', 'GS', 'MP', 'FG', 'FGA', 'FG%',
       '3P', '3PA', '3P%', '2P', '2PA', '2P%', 'eFG%', 'FT', 'FTA', 'FT%',
       'ORB', 'DRB', 'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS',
       'Year', 'W', 'L', 'W/L%', 'GB', 'PS/G',
       'PA/G', 'SRS']

In [74]:
# make the training model
train = stats[(stats["Year"] < 2024)]
test = stats[stats["Year"] == 2024]

In [75]:
# Ridge is a form of linear regression that avoids overfitting by shrinking it
from sklearn.linear_model import Ridge

reg = Ridge(alpha=.1) # controls how much the coefficient is going to be shrunk to avoid overfitting

In [76]:
reg.fit(train[predictors], train["Share"])

Ridge(alpha=0.1)

In [77]:
predictions = reg.predict(test[predictors])

In [78]:
predictions= pd.DataFrame(predictions, columns=["predictions"], index=test.index)

In [79]:
predictions

       predictions
199      -0.000203
200      -0.021090
201       0.016795
202       0.008196
203      -0.015660
...            ...
13339     0.015494
13340     0.027933
13341     0.067622
14118     0.139516
14119     0.139516

[503 rows x 1 columns]

In [80]:
combination = pd.concat([test[["Player", "Share"]], predictions], axis=1)

In [81]:
combination

                  Player  Share  predictions
199           A.J. Green  0.000    -0.000203
200    Andre Jackson Jr.  0.000    -0.021090
201         Bobby Portis  0.000     0.016795
202          Brook Lopez  0.000     0.008196
203     Chris Livingston  0.000    -0.015660
...                  ...    ...          ...
13339   Terquavion Smith  0.000     0.015494
13340      Tobias Harris  0.000     0.027933
13341       Tyrese Maxey  0.000     0.067622
14118      Nikola JokiÄ  0.935     0.139516
14119      Luka DonÄiÄ  0.572     0.139516

[503 rows x 3 columns]

In [82]:
# get the first 10 players with MVP votes
combination.sort_values("Share", ascending=False).head(10)
# the results says that Giannis has high prediction number, but we want to predict where a player will rank in the MVP voting

                        Player  Share  predictions
14118            Nikola JokiÄ  0.935     0.139516
1149   Shai Gilgeous-Alexander  0.646     0.167554
14119            Luka DonÄiÄ  0.572     0.139516
206      Giannis Antetokounmpo  0.194     0.207161
12593            Jalen Brunson  0.143     0.099247
2461              Jayson Tatum  0.087     0.113114
7474           Anthony Edwards  0.018     0.088774
3623          Domantas Sabonis  0.003     0.086975
10889             Kevin Durant  0.001     0.098904
8937            Isaiah Stewart  0.000    -0.033107

In [83]:
# The next step to evaluate how accurate/good was the Ridge algorithm in predicting the MVP Share (error metric)
from sklearn.metrics import mean_squared_error

# regression used to predict continuous number
mean_squared_error(combination["Share"], combination["predictions"])
# takes actual values and pred values and calculates error metric (difference from predictions and actual value)

0.0030402685494387545

In [84]:
combination["Share"].value_counts()
# 458 Shared values are 0, meaning no MVP votes
# need an error metric to get the top 5 players

Share
0.000    494
0.194      1
0.646      1
0.087      1
0.003      1
0.018      1
0.001      1
0.143      1
0.935      1
0.572      1
Name: count, dtype: int64

In [85]:
combination = combination.sort_values("Share", ascending=False)
combination["Rk"] = list(range(1, combination.shape[0] + 1))
combination.head(10)
# code above gets players in rank after sorting

                        Player  Share  predictions  Rk
14118            Nikola JokiÄ  0.935     0.139516   1
1149   Shai Gilgeous-Alexander  0.646     0.167554   2
14119            Luka DonÄiÄ  0.572     0.139516   3
206      Giannis Antetokounmpo  0.194     0.207161   4
12593            Jalen Brunson  0.143     0.099247   5
2461              Jayson Tatum  0.087     0.113114   6
7474           Anthony Edwards  0.018     0.088774   7
3623          Domantas Sabonis  0.003     0.086975   8
10889             Kevin Durant  0.001     0.098904   9
8937            Isaiah Stewart  0.000    -0.033107  10

In [86]:
combination = combination.sort_values("predictions", ascending=False)
combination["Predicted_Rk"] = list(range(1, combination.shape[0] + 1))
combination.head(10)

                        Player  Share  predictions   Rk  Predicted_Rk
206      Giannis Antetokounmpo  0.194     0.207161    4             1
13334              Joel Embiid  0.000     0.204127  171             2
285                Luka Dončić  0.000     0.183905  321             3
1149   Shai Gilgeous-Alexander  0.646     0.167554    2             4
656               Nikola Jokić  0.000     0.163872  316             5
14118            Nikola JokiÄ  0.935     0.139516    1             6
14119            Luka DonÄiÄ  0.572     0.139516    3             7
7411             Anthony Davis  0.000     0.130424   81             8
7422              LeBron James  0.000     0.123182   70             9
2461              Jayson Tatum  0.087     0.113114    6            10

In [87]:
combination.sort_values("Share", ascending=False).head(5)

                        Player  Share  predictions  Rk  Predicted_Rk
14118            Nikola JokiÄ  0.935     0.139516   1             6
1149   Shai Gilgeous-Alexander  0.646     0.167554   2             4
14119            Luka DonÄiÄ  0.572     0.139516   3             7
206      Giannis Antetokounmpo  0.194     0.207161   4             1
12593            Jalen Brunson  0.143     0.099247   5            12

In [88]:
# new error metric: average_precision (checks if prediction was in the top 5 ranks)
def find_ap(combination):
    actual = combination.sort_values("Share", ascending=False).head(5)
    predicted = combination.sort_values("predictions", ascending=False)
    ps = []
    found = 0
    seen = 1
    for index,row in predicted.iterrows():
        if row["Player"] in actual["Player"].values:
            found += 1
            ps.append(found / seen)
        seen += 1

    return sum(ps) / len(ps)
    # return ps

In [89]:
find_ap(combination)

0.5976190476190476

In [90]:
years = list(range(1991,2025))

In [91]:
aps = []
all_predictions = []
for year in years[5:]:
    train = stats[stats["Year"] < year]
    test = stats[stats["Year"] == year]
    reg.fit(train[predictors],train["Share"])
    predictions = reg.predict(test[predictors])
    predictions = pd.DataFrame(predictions, columns=["predictions"], index=test.index)
    combination = pd.concat([test[["Player", "Share"]], predictions], axis=1)
    all_predictions.append(combination)
    aps.append(find_ap(combination))

In [92]:
sum(aps) / len(aps) # precision algo was lower, may need to consider more factors

0.688246960617636

In [93]:
def add_ranks(predictions):
    predictions = predictions.sort_values("predictions", ascending=False)
    predictions["Predicted_Rk"] = list(range(1,predictions.shape[0]+1))
    predictions = predictions.sort_values("Share", ascending=False)
    predictions["Rk"] = list(range(1,predictions.shape[0]+1))
    predictions["Diff"] = (predictions["Rk"] - predictions["Predicted_Rk"])
    return predictions

In [94]:
add_ranks(all_predictions[1])

               Player  Share  predictions  Predicted_Rk   Rk  Diff
1541      Karl Malone  0.857     0.196878             2    1    -1
9889   Michael Jordan  0.832     0.174062             3    2    -1
13965      Grant Hill  0.327     0.130511             7    3    -4
4353     Tim Hardaway  0.207     0.063986            19    4   -15
7763        Glen Rice  0.117     0.034663            48    5   -43
...               ...    ...          ...           ...  ...   ...
8450    Jim McIlvaine  0.000     0.011260           138  381   243
3330    Ennis Whatley  0.000     0.011335           137  382   245
3331       Gary Trent  0.000     0.011363           136  383   247
12132     Byron Scott  0.000     0.011508           135  384   249
9883    Dennis Rodman  0.000    -0.056512           385  385     0

[385 rows x 6 columns]

In [95]:
def backtest(stats, model, years, predictors):
    aps = []
    all_predictions = []
    for year in years:
        train = stats[stats["Year"] < year]
        test = stats[stats["Year"] == year]
        model.fit(train[predictors],train["Share"])
        predictions = model.predict(test[predictors])
        predictions = pd.DataFrame(predictions, columns=["predictions"], index=test.index)
        combination = pd.concat([test[["Player", "Share"]], predictions], axis=1)
        combination = add_ranks(combination)
        all_predictions.append(combination)
        aps.append(find_ap(combination))
    return sum(aps) / len(aps), aps, pd.concat(all_predictions)

In [96]:
mean_ap, aps, all_predictions = backtest(stats, reg, years[5:], predictors)

In [97]:
mean_ap # same as precision algo value

0.688246960617636

In [98]:
all_predictions[all_predictions["Rk"] < 5].sort_values("Diff").head(10)

                 Player  Share  predictions  Predicted_Rk  Rk  Diff
1245         Jason Kidd  0.712     0.028690            51   2   -49
14107     Nikola JokiÄ  0.210     0.050319            53   4   -49
4786         Steve Nash  0.839     0.035298            41   1   -40
14108     Luka DonÄiÄ  0.198     0.059868            42   4   -38
14110     Nikola JokiÄ  0.961     0.064204            36   1   -35
12356       Joakim Noah  0.258     0.048092            38   4   -34
4802         Steve Nash  0.739     0.054922            34   1   -33
14099  Peja StojakoviÄ  0.228     0.049423            26   4   -22
4816         Steve Nash  0.785     0.075956            22   2   -20
4353       Tim Hardaway  0.207     0.063986            19   4   -15

In [99]:

pd.concat([pd.Series(reg.coef_), pd.Series(predictors)], axis=1).sort_values(0, ascending=False)

           0     1
13  0.126854  eFG%
18  0.029989   DRB
10  0.017951    2P
17  0.016554   ORB
12  0.013821   2P%
21  0.012968   STL
15  0.012097   FTA
22  0.011668   BLK
5   0.007093   FGA
25  0.007013   PTS
20  0.006332   AST
7   0.002498    3P
27  0.000603     W
30  0.000297    GB
0   0.000260   Age
32  0.000206  PA/G
1   0.000098     G
2   0.000005    GS
26 -0.000126  Year
33 -0.000144   SRS
28 -0.000848     L
31 -0.001050  PS/G
24 -0.002671    PF
4  -0.002889    FG
3  -0.003891    MP
16 -0.006313   FT%
14 -0.007344    FT
23 -0.009096   TOV
9  -0.010402   3P%
8  -0.011388   3PA
11 -0.016821   2PA
19 -0.023107   TRB
29 -0.049690  W/L%
6  -0.194523   FG%

In [100]:
stat_ratios = stats[["PTS", "AST", "STL", "BLK", "3P", "Year"]].groupby("Year").apply(lambda x: x/x.mean())

/var/folders/1c/94yjv4p50gj3ymb67x1rck640000gn/T/ipykernel_62467/2022889540.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  stat_ratios = stats[["PTS", "AST", "STL", "BLK", "3P", "Year"]].groupby("Year").apply(lambda x: x/x.mean())

In [101]:
stat_ratios

                 PTS       AST       STL       BLK        3P  Year
Year
1991 0      1.013982  0.410798  0.953945  0.661172  0.504895   1.0
     1      1.615686  1.004172  1.635334  0.661172  4.544056   1.0
     2      0.311995  0.091288  0.272556  1.542735  0.000000   1.0
     3      0.200568  0.182577  0.272556  0.000000  0.000000   1.0
     4      2.384530  1.597547  1.771612  0.881563  1.514685   1.0
...              ...       ...       ...       ...       ...   ...
2024 13339  0.385611  0.396570  0.852542  0.000000  0.843252   1.0
     13340  2.009850  1.536710  1.705085  1.721760  1.370285   1.0
     13341  3.026460  3.073421  1.705085  1.229829  3.162196   1.0
     14118  0.000000  0.000000  0.000000  0.000000  0.000000   1.0
     14119  0.000000  0.000000  0.000000  0.000000  0.000000   1.0

[14120 rows x 6 columns]

In [102]:
stats[["PTS_R", "AST_R", "STL_R", "BLK_R", "3P_R"]] = stat_ratios[["PTS", "AST", "STL", "BLK", "3P"]].reset_index(drop=True)

In [103]:

predictors += ["PTS_R", "AST_R", "STL_R", "BLK_R", "3P_R"]

In [104]:
mean_ap, aps, all_predictions = backtest(stats, reg, years[5:], predictors)

In [106]:
mean_ap

0.6836655804522696

In [112]:
stats["NPos"] = stats["Pos"].astype("category").cat.codes
stats["NTm"] = stats["Team"].astype("category").cat.codes

In [117]:
from sklearn.ensemble import RandomForestRegressor

rf = RandomForestRegressor(n_estimators=50, random_state=1, min_samples_split=5)

# mean_ap, aps, all_predictions = backtest(stats, rf, years[28:], predictors + ["NPos", "NTm"])
mean_ap, aps, all_predictions = backtest(stats, rf, years[28:], predictors)

In [119]:
mean_ap

0.7292878912275463

In [121]:
mean_ap, aps, all_predictions = backtest(stats, reg, years[28:], predictors)

In [122]:
mean_ap

0.6117927004685445